// Ordered campaign actions for patch 0.5. Each entry: act, area, action, useful reminder.
const questlineSteps=[
['Act 1','Riverbank','Defeat the Bloated Miller and spend your first passive point','Enter Clearfell Encampment'],
['Act 1','Clearfell Encampment','Speak with the camp NPCs','Enter Clearfell'],
['Act 1','Clearfell','Defeat Beira, the Rotten Pack','Continue to Grelwood'],
['Act 1','Grelwood','Activate the waypoint and summon Una','Enter Red Vale'],
['Act 1','Red Vale','Activate all three Obelisks of Rust and defeat the Rust King','Collect the three runed items; portal to town'],
['Act 1','Clearfell Encampment','Hand in the runed items and take the Runed Spikes','Return to Grelwood'],
['Act 1','Grelwood','Activate all three Runic Seals','Return to town, then re-enter Grelwood'],
['Act 1','Grelwood','Enter Grim Tangle','The entrance is near Una'],
['Act 1','Grim Tangle','Summon Una, activate three Runestones, summon Farrow, and defeat the boss','Enter Cemetery of the Eternals'],
['Act 1','Cemetery of the Eternals','Speak with Lachlann and enter Mausoleum of the Praetor','Defeat Draven and take his Memorial Key Piece'],
['Act 1','Tomb of the Consort','Defeat Asinia and take her Memorial Key Piece','Return to the Cemetery'],
['Act 1','Cemetery of the Eternals','Speak with, then defeat Lachlann of Endless Lament','Take Count Lachlann’s Ring and portal to town'],
['Act 1','Clearfell Encampment','Speak with NPCs, then waypoint to Hunting Grounds','Continue the main path'],
['Act 1','Hunting Grounds','Speak with Delwyn and defeat the Crowbell','Enter Freythorn'],
['Act 1','Freythorn','Complete the rituals and defeat the King in the Mists','Speak with Finn; portal to town'],
['Act 1','Hunting Grounds','Waypoint here, then enter Ogham Farmlands','Continue toward the village'],
['Act 1','Ogham Farmlands','Activate the waypoint and collect Una’s Lute before the farms','Enter Ogham Village'],
['Act 1','Ogham Village','Collect Smithing Tools, return them to Renly, then return to the village','Optional league unlock: salvage bench'],
['Act 1','Ogham Village','Defeat the Executioner, use the lever, and speak with Leitis','Enter Manor Ramparts'],
['Act 1','Manor Ramparts','Activate the waypoint; return to town to claim rewards','Waypoint back and enter Ogham Manor'],
['Act 1','Ogham Manor','Defeat Candlemass, then descend to the arena','Defeat Count Geonor'],
['Act 1','Clearfell Encampment','Speak with the Hooded One and the camp NPCs','Travel to Act 2'],
['Act 2','Vastiri Outskirts','Defeat Rathbreaker','Portal to Ardura Caravan and speak with Zarka'],
['Act 2','Ardura Caravan','Use the Desert Map to travel to Mawdun Quarry','Enter Mawdun Mine'],
['Act 2','Mawdun Mine','Activate the waypoint, defeat Rudja, open Risu’s cage, and speak with her','Portal to town'],
['Act 2','Ardura Caravan','Use the Desert Map to travel to Traitor’s Passage','Continue toward the gates'],
['Act 2','Traitor’s Passage','Activate the Ancient Seal and all three Runic Seals','Defeat Balbala and take Balbala’s Barya'],
['Act 2','Halani Gates','Summon Asala and defeat Jamanra, the Risen King','Enter the sandstorm; portal to town'],
['Act 2','Ardura Caravan','Use the Desert Map to travel to Keth','Continue to the Lost City'],
['Act 2','Keth','Collect the Kabala Clan Relic and defeat Kabala, Constrictor Queen','Enter Lost City'],
['Act 2','Lost City','Travel through Buried Shrines','Enter Heart of Keth'],
['Act 2','Heart of Keth','Defeat Azarian, speak with the Water Goddess, take the Everburning Cinders and Essence of Water','Portal to town'],
['Act 2','Ardura Caravan','Use the Desert Map to travel to Mastodon Badlands','Enter Lightless Passage'],
['Act 2','Lightless Passage','Enter the Well of Souls','Speak with the Lurking Creature and Sin; return to Mastodon Badlands'],
['Act 2','Mastodon Badlands','Enter Bone Pits','Continue to Blackrib Pit'],
['Act 2','Bone Pits','Collect the Sun Clan Relic; defeat Iktab and Ekbab in Blackrib Pit','Take Mastodon Tusks; portal to town'],
['Act 2','Ardura Caravan','Use the Desert Map to travel to Valley of the Titans','Activate the Medallion and three Ancient Seals'],
['Act 2','Titan Grotto','Defeat Zalmarath, the Colossus','Take the Flame Ruby; portal to town'],
['Act 2','Ardura Caravan','Receive the Horn of the Vastiri, sound it at the caravan in Traitor’s Passage','Travel to Deshar'],
['Act 2','Deshar','Find Lailuma’s body and the Final Letter; defeat Hunin and Mugin','Take the Djinn Barya and enter Path of Mourning'],
['Act 2','Path of Mourning','Travel through the area','Enter Spires of Deshar'],
['Act 2','Spires of Deshar','Activate the Sisters of Garukhan shrine and defeat Tor Gul','Portal to town and claim rewards'],
['Act 2','Dreadnought','Defeat Jamanra, the Abomination','Return to town and travel to Act 3'],
['Act 3','Sandswept Marsh','Travel to Ziggurat Encampment','Speak with the camp NPCs'],
['Act 3','Jungle Ruins','Defeat Mighty Silverfist','Enter Venom Crypts'],
['Act 3','Venom Crypts','Take Corpse-snake Venom from the corpse at the end','Portal to town and give it to Servi'],
['Act 3','Jungle Ruins','Return and enter Infested Barrens','Travel to Chimeral Wetlands'],
['Act 3','Chimeral Wetlands','Defeat Xyclucian, the Chimera','Take the Chimeral Inscribed Ultimatum and enter Jiquani’s Machinarium'],
['Act 3','Jiquani’s Machinarium','Summon Alva, collect Small Soul Cores, activate Stone Altars, and defeat Blackjaw','Enter Jiquani’s Sanctum'],
['Act 3','Jiquani’s Sanctum','Find three Medium Soul Cores, start both generators, activate the Large Soul Core, and defeat Zicoatl','Waypoint back to Jungle Ruins'],
['Act 3','Jungle Ruins','Activate the Stone Altar near the waypoint','Enter Matlan Waterways'],
['Act 3','Matlan Waterways','Stand on every pressure plate and pull the canal lever','Enter Azak Bog'],
['Act 3','Azak Bog','Summon Servi, defeat Ignagduk, and take the Ghastly Spear','Portal to town'],
['Act 3','Ziggurat Encampment','Speak with Alva below the stairs','Enter Drowned City'],
['Act 3','Drowned City','Summon Oswald','Enter Molten Vault'],
['Act 3','Molten Vault','Use the levers, defeat Mektul, take the Hammer of Kamasa, and speak with Oswald','Optional league unlock: reforging bench'],
['Act 3','Drowned City','Return and enter Apex of Filth','Defeat Queen of Filth and take the Temple Door Idol'],
['Act 3','Ziggurat Encampment','Speak with Alva and open the temple door','Enter Temple of Kopec'],
['Act 3','Temple of Kopec','Climb the stairs twice, defeat Ketzuli, investigate the platform with Alva, and enter the gateway','Descend to Utzaal'],
['Act 3','Utzaal','Defeat Viper Napuatzi and obtain the Sacrificial Heart','Enter Aggorat'],
['Act 3','Aggorat','Take the Sacrificial Dagger, sacrifice the Heart at the altar','Enter Black Chambers'],
['Act 3','Black Chambers','Defeat Doryani and Doryani’s Triumph','Speak with Doryani, return to town, then travel to Act 4'],
['Act 4','Kingsmarch','Speak with NPCs, obtain the Book Charter, and speak with Makoru','Sail to Kedge Bay'],
['Act 4','Kedge Bay','Collect the Ripped Map Piece from Dead Man’s Chest','Enter Journey’s End'],
['Act 4','Journey’s End','Summon Tujen, defeat Captain Hartlin, and take Verisium Ingots','Portal to town'],
['Act 4','Kingsmarch','Speak with Dannig to receive Verisium Spikes','Waypoint back to Journey’s End'],
['Act 4','Journey’s End','Speak with Freya, activate the Karui Totems, and defeat Omniphobia','Return to Kingsmarch and claim the skill points'],
['Act 4','Kingsmarch','Sail to the required islands shown by the current league’s quest','One island holds Matiki; rescue her to unlock Eye of Hinekora'],
['Act 4','Whakapanu Island','Collect the Frayed Map Piece, defeat Great White One, and take the Shark Fin','Enter Singing Caverns'],
['Act 4','Singing Caverns','Defeat Diamora, Song of Death','Speak with the Hooded One and return to the ship'],
['Act 4','Ngakanu','Give the Shark Fin to Kaimana if obtained','Return to the ship'],
['Act 4','Abandoned Prison','Farm the Chapel Key, open the chapel, activate Goddess of Justice, and use the levers','Enter Solitary Confinement'],
['Act 4','Solitary Confinement','Use the levers and defeat the Prisoner','Speak with the Hooded One and return to the ship'],
['Act 4','Isle of Kin','Collect the Torn Map Piece','Enter Volcanic Warrens'],
['Act 4','Volcanic Warrens','Defeat Krutog, Lord of Kin','Return to the ship'],
['Act 4','Shrike Island','Collect the Ragged Map Piece and defeat Scourge of the Skies','Return to the ship'],
['Act 4','Eye of Hinekora','Speak with Matiki, activate the well, and complete the three tests','Pay respects at Silent Hall; enter Halls of the Dead'],
['Act 4','Halls of the Dead','Complete Tawhoa, Tasalio, and Ngamahu’s tests; defeat Yama the White','Take the Silver Coin; enter Trial of the Ancestors'],
['Act 4','Trial of the Ancestors','Speak with Navali and take the Tattoo of Hinekora','Return to the ship'],
['Act 4','Arastas','Speak with Missionary Lorandis, enter and exit the church, destroy the forcefield, and defeat Torvian','Enter the Excavation'],
['Act 4','Excavation','Defeat Benedictus and speak with the Hooded One','Return to Kingsmarch'],
['Act 4','Ngakanu','Enter Heart of the Tribe','Defeat Tavakai’s three forms'],
['Act 4','Kingsmarch','Give all four map pieces to Makoru','Sail to Plunder’s Point'],
['Act 4','Plunder’s Point','Complete the expedition and enter the Deserted Post','Unlock the Ancient Runes, then return to town'],
['Interlude: Mount Kriar','The Glade','Speak with NPCs','Enter Ashen Forest'],
['Interlude: Mount Kriar','Ashen Forest','Travel through the forest','Enter Kriar Village'],
['Interlude: Mount Kriar','Kriar Village','Defeat Lythara, the Wayward Spear','Enter Glacial Tarn'],
['Interlude: Mount Kriar','Glacial Tarn','Travel through the tarn','Enter Howling Caves'],
['Interlude: Mount Kriar','Howling Caves','Defeat the Abominable Yeti and take the Icy Tusks','Return to town; speak with Hilda for skill points'],
['Interlude: Mount Kriar','Glacial Tarn','Defeat Rakkar, the Frozen Talon','Enter Kriar Peaks'],
['Interlude: Mount Kriar','Kriar Peaks','Take Elder Madox’s gift','Enter Etched Ravine'],
['Interlude: Mount Kriar','Etched Ravine','Defeat Stormgore, the Guardian','Enter Cuachic Vault'],
['Interlude: Mount Kriar','Cuachic Vault','Defeat Zelina and Zolin, then summon Doryani','Return to town'],
['Interlude: Ogham','The Refuge','Speak with NPCs','Enter Scorched Farmlands'],
['Interlude: Ogham','Scorched Farmlands','Defeat Heldra and Isolde','Enter Stones of Serle'],
['Interlude: Ogham','Stones of Serle','Activate every Runed Megalith, defeat Siora, and speak with Una','Return through Scorched Farmlands'],
['Interlude: Ogham','Blackwood','Travel through Blackwood','Enter Holten'],
['Interlude: Ogham','Holten','Travel to Wolvenhold','Defeat Oswin, the Dread Warden'],
['Interlude: Ogham','Holten Estate','Defeat Thane Wulfric and Lady Elswyth','Return to town'],
['Interlude: Vastiri','The Khari Bazaar','Speak with NPCs','Enter Khari Crossing'],
['Interlude: Vastiri','Khari Crossing','Defeat Akthi and Anundr','Return to town and speak with Risu for skill points'],
['Interlude: Vastiri','Khari Crossing','Collect the Molten One’s Gift from Skullmaw Stairway','Enter Pools of Khatal'],
['Interlude: Vastiri','Pools of Khatal','Travel through the pools','Enter Sel Khari Sanctuary'],
['Interlude: Vastiri','Sel Khari Sanctuary','Defeat Elzarah, the Cobra Lord and speak with Asala','Return to town'],
['Interlude: Vastiri','Khari Crossing','Enter Galai Gates','Defeat Vornas, the Fell Flame'],
['Interlude: Vastiri','Qimah','Activate the Seven Pillars and summon Jado','Enter Qimah Reservoir'],
['Interlude: Vastiri','Qimah Reservoir','Defeat Azmadi and activate the Grand Barya','Speak with Jado and return to town'],
['Endgame','Kingsmarch','Speak with the Hooded One after completing the Interludes','Travel to Oriath'],
['Endgame','Ziggurat Refuge','Speak with the Hooded One and Doryani','Run the first map and begin mapping from your hideout']
];
