// Complete ordered route based on the PoE 2 Wiki Acts quick guide for patch 0.5.
// Each numbered Wiki instruction is retained as its own step; waypoint is always written in full.
const questlineSteps=[
// Act 1
['Act 1','Riverbank','Defeat the Bloated Miller, use the skill point, and enter Clearfell Encampment',''],
['Act 1','Clearfell Encampment','Talk to the NPCs, then enter Clearfell',''],
['Act 1','Clearfell','Defeat Beira of the Rotten Pack, then enter Grelwood',''],
['Act 1','Grelwood','Activate the waypoint, summon Una near the waypoint, then enter Red Vale on the opposite side',''],
['Act 1','Red Vale','Activate all three Obelisks of Rust and defeat the Rust King','Take the Runed Girdle, Runed Guard, and Runed Skull Cap, then use a portal to town'],
['Act 1','Clearfell Encampment','Talk to the NPCs to receive the Runed Spikes, then use the waypoint to return to Grelwood',''],
['Act 1','Grelwood','Activate all three Runic Seals, then use a portal to town',''],
['Act 1','Clearfell Encampment','Talk to the NPCs, then return to Grelwood',''],
['Act 1','Grelwood','Enter Grim Tangle northwest of Una',''],
['Act 1','Grim Tangle','Summon Una, activate the three Runestones at the end of the area, summon Farrow, and defeat the boss','Enter Cemetery of the Eternals'],
['Act 1','Cemetery of the Eternals','Talk to Lachlann, enter Mausoleum of the Praetor, defeat Draven, and take Draven’s Memorial Key Piece','Return to Cemetery of the Eternals'],
['Act 1','Cemetery of the Eternals','Enter Tomb of the Consort opposite the waypoint, defeat Asinia, and take Asinia’s Memorial Key Piece','Return to Cemetery of the Eternals'],
['Act 1','Cemetery of the Eternals','Talk to Lachlann, defeat Lachlann of Endless Lament, and take Count Lachlann’s Ring','Use a portal to town'],
['Act 1','Clearfell Encampment','Talk to the NPCs, then use the waypoint to travel to Hunting Grounds',''],
['Act 1','Hunting Grounds','Talk to Delwyn, defeat the Crowbell, then enter Freythorn',''],
['Act 1','Freythorn','Complete every ritual, defeat the King in the Mists, and talk to Finn','Use a portal to town'],
['Act 1','Clearfell Encampment','Talk to the NPCs, use the waypoint to travel to Hunting Grounds, then enter Ogham Farmlands',''],
['Act 1','Ogham Farmlands','Activate the waypoint, take Una’s Lute from Una’s Lute Box before the farms, then enter Ogham Village',''],
['Act 1','Ogham Village','Once per league: activate the waypoint and take the Smithing Tools','Use a portal to town, give the tools to Renly, then return to Ogham Village'],
['Act 1','Ogham Village','Defeat the Executioner at the end of the area, use the lever, talk to Leitis, then enter Manor Ramparts',''],
['Act 1','Manor Ramparts','Activate the waypoint, return to town, and talk to the NPCs for two skill points','Use the waypoint to return to Manor Ramparts, then enter Ogham Manor'],
['Act 1','Ogham Manor','Defeat Candlemass the Living Rite, descend the stairs to the arena, and defeat Count Geonor','Use a portal to town'],
['Act 1','Clearfell Encampment','Talk to the NPCs and the Hooded One, then travel to Act 2',''],

// Act 2
['Act 2','Vastiri Outskirts','Defeat Rathbreaker, use a portal to town, talk to Zarka, then enter Ardura Caravan',''],
['Act 2','Ardura Caravan','Talk to the NPCs, then use the Desert Map to travel to Mawdun Quarry',''],
['Act 2','Mawdun Quarry','Travel through Mawdun Quarry and enter Mawdun Mine',''],
['Act 2','Mawdun Mine','Activate the waypoint, defeat Rudja the Dread Engineer, open the cage, and talk to Risu','Use a portal to town'],
['Act 2','Ardura Caravan','Talk to the NPCs, then use the Desert Map to travel to Traitor’s Passage',''],
['Act 2','Traitor’s Passage','Activate the waypoint and the Ancient Seal in the middle of the area, activate all three Runic Seals, and defeat Balbala the Traitor','Take Balbala’s Barya, then enter Halani Gates'],
['Act 2','Halani Gates','Activate the waypoint, summon Asala, defeat Jamanra the Risen King, and enter the sandstorm','Use a portal to town'],
['Act 2','Ardura Caravan','Talk to the NPCs, then use the Desert Map to travel to Keth',''],
['Act 2','Keth','Collect the Kabala Clan Relic from serpents and defeat Kabala the Constrictor Queen','Enter Lost City'],
['Act 2','Lost City','Enter Buried Shrines, then continue into Heart of Keth',''],
['Act 2','Heart of Keth','Defeat Azarian the Forsaken Son, talk to the Water Goddess, take the Everburning Cinders, ignite the Water Goddess, and take the Essence of Water','Use a portal to town'],
['Act 2','Ardura Caravan','Talk to the NPCs, then use the Desert Map to travel to Mastodon Badlands',''],
['Act 2','Mastodon Badlands','Enter Lightless Passage near the center of the area, then enter Well of Souls',''],
['Act 2','Well of Souls','Talk to the Lurking Creature to reveal Desecrated modifiers, then talk to Sin','Use the waypoint to travel to Lightless Passage, then return to Mastodon Badlands'],
['Act 2','Mastodon Badlands','Enter Bone Pits',''],
['Act 2','Bone Pits','Activate the waypoint, collect the Sun Clan Relic from monsters, enter Blackrib Pit, defeat Iktab and Ekbab, and take the Mastodon Tusks','Use a portal to town'],
['Act 2','Ardura Caravan','Talk to the NPCs, then use the Desert Map to travel to Valley of the Titans',''],
['Act 2','Valley of the Titans','Activate the waypoint, activate the Medallion near the waypoint, activate all three Ancient Seals, then enter Titan Grotto',''],
['Act 2','Titan Grotto','Defeat Zalmarath the Colossus and take the Flame Ruby','Use a portal to town'],
['Act 2','Ardura Caravan','Talk to the NPCs to receive the Horn of the Vastiri, use the Desert Map to travel to Traitor’s Passage, go to the front of the caravan, and sound the Horn','Talk to the NPCs, then use the Desert Map to travel to Deshar'],
['Act 2','Deshar','Find Lailuma’s body and take the Final Letter, defeat Hunin and Mugin, and take the Djinn Barya','Enter Path of Mourning'],
['Act 2','Path of Mourning','Travel through Path of Mourning and enter Spires of Deshar',''],
['Act 2','Spires of Deshar','Activate the waypoint, activate the Sisters of Garukhan shrine, and defeat Tor Gul the Defiler','Use a portal to town'],
['Act 2','Ardura Caravan','Talk to the NPCs to receive two skill points, then use the Desert Map to travel to Dreadnought',''],
['Act 2','Dreadnought','Activate the waypoint and defeat Jamanra the Abomination','Use a portal to town'],
['Act 2','Ardura Caravan','Talk to the NPCs and Asala, then travel to Act 3',''],

// Act 3
['Act 3','Sandswept Marsh','Travel through Sandswept Marsh and enter Ziggurat Encampment',''],
['Act 3','Ziggurat Encampment','Talk to the NPCs, then use the northern exit to enter Jungle Ruins',''],
['Act 3','Jungle Ruins','Defeat Mighty Silverfist, then enter Venom Crypts near the waypoint in the center of the area',''],
['Act 3','Venom Crypts','Take the Corpse-snake Venom from the corpse at the end of the area','Use a portal to town'],
['Act 3','Ziggurat Encampment','Give the Corpse-snake Venom to Servi and choose a permanent bonus','Use the waypoint to return to Jungle Ruins, then enter Infested Barrens opposite the waypoint'],
['Act 3','Infested Barrens','Activate the waypoint, then enter Chimeral Wetlands opposite Azak Bog',''],
['Act 3','Chimeral Wetlands','Activate the waypoint, defeat Xyclucian the Chimera, and take the Chimeral Inscribed Ultimatum','Enter Jiquani’s Machinarium from the boss arena'],
['Act 3','Jiquani’s Machinarium','Activate the waypoint, summon Alva, collect Small Soul Cores, and activate the Stone Altars','Defeat Blackjaw the Remnant, then enter Jiquani’s Sanctum'],
['Act 3','Jiquani’s Sanctum','Activate the waypoint, summon Alva, find three Medium Soul Cores, and start both generators in the corners of the area','Activate the Large Soul Core near Alva, defeat Zicoatl, take the Large Soul Core, then use the waypoint to travel to Jungle Ruins'],
['Act 3','Jungle Ruins','Activate the Stone Altar near the waypoint, then enter Matlan Waterways',''],
['Act 3','Matlan Waterways','Stand on every pressure plate, pull the large Canal Lever at the end, then enter Azak Bog',''],
['Act 3','Azak Bog','Activate the waypoint, summon Servi, defeat Ignagduk the Bog Witch, and take Ignagduk’s Ghastly Spear','Use a portal to town'],
['Act 3','Ziggurat Encampment','Descend the stairs, talk to Alva, then enter Drowned City',''],
['Act 3','Drowned City','Activate the waypoint, summon Oswald, then enter Molten Vault',''],
['Act 3','Molten Vault','Once per league: activate the waypoint, use the lever, pull the Sluice Gate Lever, defeat Mektul the Forgemaster, and take the Hammer of Kamasa','Talk to Oswald to unlock the reforging bench, then use a portal to town'],
['Act 3','Ziggurat Encampment','Talk to the NPCs, use the waypoint to travel to Drowned City, then enter Apex of Filth',''],
['Act 3','Apex of Filth','Activate the waypoint, defeat the Queen of Filth at the end, and take the Temple Door Idol','Use a portal to town'],
['Act 3','Ziggurat Encampment','Descend the stairs, talk to Alva, open the door, then enter Temple of Kopec',''],
['Act 3','Temple of Kopec','Climb the stairs twice at the corner of the pyramid, defeat Ketzuli, summon Alva, and investigate the platform','Enter the gateway, activate the waypoint behind it, descend the stairs, then enter Utzaal'],
['Act 3','Utzaal','Activate the waypoint, defeat Viper Napuatzi, and defeat monsters until the Sacrificial Heart drops','Enter Aggorat'],
['Act 3','Aggorat','Activate the waypoint, go to the altar, take the Sacrificial Dagger, place the Sacrificial Heart, and stab it for two skill points','Enter Black Chambers'],
['Act 3','Black Chambers','Activate the waypoint, defeat Doryani and Doryani’s Triumph, talk to Doryani, use a portal to town, then talk to Doryani for the apocalypse',''],
['Act 3','Ziggurat Encampment','Talk to the NPCs and Alva, then travel to Act 4',''],

// Act 4
['Act 4','Kingsmarch','Talk to the NPCs to receive the Book Charter, talk to Makoru, then sail to Kedge Bay',''],
['Act 4','Kedge Bay','Open Dead Man’s Chest and take the Ripped Map Piece, then enter Journey’s End',''],
['Act 4','Journey’s End','Summon Tujen, defeat Captain Hartlin at the end of the area, and take the Verisium Ingots','Use a portal to town'],
['Act 4','Kingsmarch','Talk to Dannig to receive the Verisium Spikes, then use the waypoint to travel to Journey’s End',''],
['Act 4','Journey’s End','Talk to Freya, activate the Karui Totems, and defeat Omniphobia','Use a portal to town'],
['Act 4','Kingsmarch','Talk to Tujen to receive two skill points, talk to Makoru, then sail to Whakapanu Island',''],
['Act 4','Whakapanu Island','Search the Petrified Pirate and take the Frayed Map Piece, defeat the Great White One, and take the Shark Fin','Enter Singing Caverns'],
['Act 4','Singing Caverns','Activate the waypoint, defeat Diamora at the end of the area, talk to the Hooded One, then return to the ship',''],
['Act 4','Ship','Talk to Makoru, then sail to Ngakanu',''],
['Act 4','Ngakanu','Talk to Kaimana and hand over the Shark Fin for the permanent defence choice, then return to the ship',''],
['Act 4','Ship','Talk to Makoru, then sail to Abandoned Prison',''],
['Act 4','Abandoned Prison','Defeat monsters until the Chapel Key drops, open the Chapel Door, activate the waypoint, and activate the Goddess of Justice','Use the levers, then enter Solitary Confinement'],
['Act 4','Solitary Confinement','Use the levers, defeat the Prisoner at the end, talk to the Hooded One, then return to the ship',''],
['Act 4','Ship','Talk to Makoru, then sail to Isle of Kin',''],
['Act 4','Isle of Kin','Search the Flayed Sailor on the coastline and take the Torn Map Piece','Optionally defeat the Blind Beast, then enter Volcanic Warrens'],
['Act 4','Volcanic Warrens','Defeat Krutog at the end of the area, talk to the Hooded One, then return to the ship',''],
['Act 4','Ship','Talk to Makoru, then sail to Shrike Island',''],
['Act 4','Shrike Island','Search the Corpse Nest near the end and take the Ragged Map Piece, defeat the Scourge of the Skies, talk to the Hooded One, then return to the ship',''],
['Act 4','Ship','Talk to Makoru, then sail to Eye of Hinekora','Matiki must be rescued from the league’s designated island before this destination is available'],
['Act 4','Eye of Hinekora','Talk to the NPCs, activate the Well of Hinekora, pass all three tests, and choose Pay Your Respects for the permanent Mana bonus','Continue farther down and enter Halls of the Dead'],
['Act 4','Halls of the Dead','Activate the waypoint, pass Tawhoa’s test, pass Tasalio’s test, pass Ngamahu’s test, and defeat Yama the White','Take the Silver Coin, then enter Trial of the Ancestors'],
['Act 4','Trial of the Ancestors','Activate the waypoint, talk to Navali, and take the Tattoo of Hinekora for two skill points','Return to the ship'],
['Act 4','Ship','Talk to Makoru, then sail to Arastas',''],
['Act 4','Arastas','Activate the waypoint, talk to Missionary Lorandis, enter the church, exit the church, destroy the forcefield, and defeat Torvian','Enter the Excavation'],
['Act 4','Excavation','Defeat Benedictus, enter the forge, talk to the Hooded One, then use a portal to town',''],
['Act 4','Kingsmarch','Talk to the NPCs, talk to Rhodri at the ship, then sail to Ngakanu',''],
['Act 4','Ngakanu','Enter Heart of the Tribe',''],
['Act 4','Heart of the Tribe','Activate the waypoint and defeat Tavakai the Chieftain, Tavakai the Fallen, and Tavakai the Consumed','Use a portal to town'],
['Act 4','Kingsmarch','Talk to Makoru at the ship about the four map pieces, then sail to Plunder’s Point',''],
['Act 4','Plunder’s Point','Complete the expedition, enter the Deserted Post to unlock all runes, return to the ship, then use the waypoint to return to town',''],
['Act 4','Kingsmarch','Talk to the NPCs and the Hooded One, then choose Ogham, Vastiri, or Mount Kriar','The three Interludes may be completed in any order'],

// Interlude: Mount Kriar
['Interlude: Mount Kriar','The Glade','Talk to the NPCs, then enter Ashen Forest',''],
['Interlude: Mount Kriar','Ashen Forest','Travel through Ashen Forest and enter Kriar Village',''],
['Interlude: Mount Kriar','Kriar Village','Activate the waypoint, defeat Lythara the Wayward Spear, then enter Glacial Tarn',''],
['Interlude: Mount Kriar','Glacial Tarn','Activate the waypoint, then enter Howling Caves',''],
['Interlude: Mount Kriar','Howling Caves','Activate the waypoint, defeat the Abominable Yeti, and take the Icy Tusks','Use a portal to town'],
['Interlude: Mount Kriar','The Glade','Talk to Hilda to receive two skill points, then use the waypoint to travel to Glacial Tarn',''],
['Interlude: Mount Kriar','Glacial Tarn','Defeat Rakkar the Frozen Talon, then enter Kriar Peaks',''],
['Interlude: Mount Kriar','Kriar Peaks','Activate the waypoint, take the gift from Elder Madox, then enter Etched Ravine',''],
['Interlude: Mount Kriar','Etched Ravine','Activate the waypoint, defeat Stormgore the Guardian, then enter Cuachic Vault',''],
['Interlude: Mount Kriar','Cuachic Vault','Activate the waypoint, defeat Zelina and Zolin, summon Doryani, then use a portal to town',''],

// Interlude: Ogham
['Interlude: Ogham','The Refuge','Talk to the NPCs, then use the southern exit to enter Scorched Farmlands',''],
['Interlude: Ogham','Scorched Farmlands','Defeat Heldra of the Black Pyre and Isolde of the White Shroud, then enter Stones of Serle',''],
['Interlude: Ogham','Stones of Serle','Activate every Runed Megalith, go to the central rune, defeat Siora, talk to Una, then return to Scorched Farmlands',''],
['Interlude: Ogham','Scorched Farmlands','Enter the darkness near the bosses, enter Blackwood, then continue to Holten',''],
['Interlude: Ogham','Holten','Travel through Holten and enter Wolvenhold',''],
['Interlude: Ogham','Wolvenhold','Defeat Oswin the Dread Warden, return to Holten, then enter Holten Estate',''],
['Interlude: Ogham','Holten Estate','Activate the waypoint, go upstairs and then downstairs, and defeat Thane Wulfric and Lady Elswyth on the ground floor','Use a portal to town'],
['Interlude: Ogham','The Refuge','Talk to the NPCs and the Hooded One, then travel to Vastiri',''],

// Interlude: Vastiri
['Interlude: Vastiri','The Khari Bazaar','Talk to the NPCs, then enter Khari Crossing',''],
['Interlude: Vastiri','Khari Crossing','Defeat Akthi and Anundr in the northeast, then use a portal to town',''],
['Interlude: Vastiri','The Khari Bazaar','Talk to Risu to receive two skill points, then return to Khari Crossing',''],
['Interlude: Vastiri','Khari Crossing','Enter Skullmaw Stairway in the northwest and take the Molten One’s Gift for the permanent Life bonus','Return to Khari Crossing, then enter Pools of Khatal in the southwest'],
['Interlude: Vastiri','Pools of Khatal','Activate the waypoint, then enter Sel Khari Sanctuary',''],
['Interlude: Vastiri','Sel Khari Sanctuary','Activate the waypoint, defeat Elzarah the Cobra Lord, talk to Asala, then use a portal to town',''],
['Interlude: Vastiri','The Khari Bazaar','Talk to the NPCs, enter Khari Crossing, then enter Galai Gates to the west',''],
['Interlude: Vastiri','Galai Gates','Activate the waypoint, defeat Vornas the Fell Flame, then enter Qimah',''],
['Interlude: Vastiri','Qimah','Activate the waypoint, activate the Seven Pillars for the permanent choice, summon Jado at the end, then enter Qimah Reservoir',''],
['Interlude: Vastiri','Qimah Reservoir','Activate the waypoint, defeat Azmadi, activate the Grand Barya, talk to Jado, then use a portal to town',''],
['Interlude: Vastiri','The Khari Bazaar','Talk to the NPCs and the Hooded One, then travel to Mount Kriar',''],

// Endgame
['Endgame','Campaign','Use a waypoint to travel to Kingsmarch in Act 4',''],
['Endgame','Kingsmarch','Talk to the NPCs and the Hooded One to receive two skill points, then travel to Oriath',''],
['Endgame','The Ziggurat Refuge','Talk to the NPCs, click the Hooded One to the right of the waypoint, and talk to Doryani','Run one map in the Ziggurat to unlock maps, then begin mapping from your hideout']
];

// Permanent boosts are metadata, attached to the matching step only in the All view.
const questlineRewards=[
['Act 1','Clearfell','Beira','+10% Cold Resistance'],['Act 1','Hunting Grounds','Crowbell','+2 Weapon Set Passive Skill Points'],['Act 1','Freythorn','King in the Mists','+30 Spirit'],['Act 1','Ogham Farmlands','Una’s Lute','+2 Weapon Set Passive Skill Points'],['Act 1','Ogham Manor','Candlemass','+20 maximum Life'],
['Act 2','Keth','Kabala','+2 Weapon Set Passive Skill Points'],['Act 2','Valley of the Titans','Medallion','+1 Charm Slot; choose Charm Charges or Mana Recovery from Flasks'],['Act 2','Deshar','Final Letter','+2 Weapon Set Passive Skill Points'],['Act 2','Spires of Deshar','Sisters of Garukhan','+10% Lightning Resistance'],
['Act 3','Jungle Ruins','Mighty Silverfist','+2 Weapon Set Passive Skill Points'],['Act 3','Ziggurat Encampment','Corpse-snake Venom','Choose Stun Threshold, Elemental Ailment Threshold, or Mana Regeneration'],['Act 3','Jiquani’s Machinarium','Blackjaw','+10% Fire Resistance'],['Act 3','Azak Bog','Ignagduk','+30 Spirit'],['Act 3','Aggorat','Sacrificial Heart','+2 Weapon Set Passive Skill Points'],
['Act 4','Kingsmarch','Tujen to receive two skill points','+2 Weapon Set Passive Skill Points'],['Act 4','Ngakanu','Shark Fin','Choose Armour/Evasion/ES or hybrid defence bonus'],['Act 4','Eye of Hinekora','Pay Your Respects','+5% maximum Mana'],['Act 4','Halls of the Dead','Tawhoa’s test','Three tattoo choices: resistance or attribute'],['Act 4','Trial of the Ancestors','Tattoo of Hinekora','+2 Weapon Set Passive Skill Points'],['Act 4','Abandoned Prison','Goddess of Justice','Choose Life or Mana Recovery from Flasks'],
['Interlude: Mount Kriar','Kriar Village','Lythara','+40 Spirit'],['Interlude: Mount Kriar','The Glade','Hilda','+2 Weapon Set Passive Skill Points'],['Interlude: Ogham','Wolvenhold','Oswin','+2 Weapon Set Passive Skill Points'],['Interlude: Vastiri','The Khari Bazaar','Risu','+2 Weapon Set Passive Skill Points'],['Interlude: Vastiri','Khari Crossing','Molten One’s Gift','+5% maximum Life'],['Interlude: Vastiri','Qimah','Seven Pillars','Choose Attributes, Defences, Presence, Cooldown Recovery, Movement Speed, Resists, or Experience'],['Endgame','Kingsmarch','two skill points','+2 Weapon Set Passive Skill Points']
];
function questRewardFor(step){return questlineRewards.find(([act,area,needle])=>step.act===act&&step.area===area&&`${step.objective} ${step.bonus}`.includes(needle));}
function enrichQuestline(steps){return steps.map(step=>{if(step.type!=='questline')return step;const reward=questRewardFor(step);if(!reward||step.bonus.includes(reward[3]))return step;return{...step,bonus:[step.bonus,reward[3]].filter(Boolean).join(' · ')};});}
function stripQuestlineRewards(steps){return steps.map(step=>{if(step.type!=='questline')return step;const reward=questRewardFor(step);if(!reward)return step;return{...step,bonus:step.bonus.replace(` · ${reward[3]}`,'').replace(reward[3],'').trim()};});}
